### ISSUE TITLE
"KeePassHttp is not running" error in Pass|Fox

### ISSUE THREAD

**Issue by MyerSmith** [droidmonkey/keepassx_http#2]
I get this error in Firefox 47.0.1 with the lastest Pass|Fox plugin. The chrome Plugin chomepass works fine with keepassx_http. 

maybe related to this 
https://github.com/droidmonkey/keepassx_http/commit/51bfbc964e778fd0fb00562931ca51c53946f5c7

how can I debug this ?

**Comment by droidmonkey** [comment]
Did this start occurring after you updated to the build you referenced?

**Comment by droidmonkey** [comment]
I reverted the code base to 175167b311390b665ac3d7484cdb5a298944c854 and PassIFox still failed to populate the username and password fields. This might be a more systemic issue between PassIFox and this implementation of keepass_http.

**Comment by anonymousreport1** [comment]
I am using Firefox 47.0.1 and the latest version of PassIFox (11th of June 2016) on OS X 10.11.5. I only get the error "KeePassHttp is not running" when I either don't have a database connected or the database is locked (both expected behavior?). Everything works for me as expected.

How can I reproduce this error?

**Comment by MyerSmith** [comment]
Did this start occurring after you updated to the build you referenced? 

Yes after a update. Don't know if the browser plugin also got a update in last time.
When I delete permissions and stored keys database in keepassx and use a fresh browser profile, the plugin shows me a connect Button but keepassx don't open a popup for permissions like in chromium.

**Comment by droidmonkey** [comment]
I observed that it connected to the keepass_http agent just fine and correctly identified websites that had stored credentials. It offered me to select a credential, I did, then hit OK and it does nothing (ie it does not fill in the form fields).

**Comment by droidmonkey** [comment]
Looks like the plugin was updated, I no longer observe this error. Pleas ensure your plugin is at version 1.2.0.

**Comment by yeawellwhatever** [comment]
Currently on version 1.2.2, I'm still having this issue. 
Vivaldi works fine for me with ChromIPass
