### ISSUE TITLE
Crash when PassIFox requests a password with more than one open database

### ISSUE THREAD

**Issue by anonymousreport1** [droidmonkey/keepassx_http#3]
**Steps to reproduce**
1. Create two databases
2. Open them both
3. Connect one of the two databases with the browser plugin PassIFox
4. Make sure "_Search in all open databases for matching entries_" is checked in
`KeePassX > Preferences > Http > Advanced`
5. Create an entry in one of the databases for a website
6. Go to the website's login form

**Current behavior**
KeePassX crashes and opens a OS X dialog for error reporting. It shows a very long crash dump.

**Expected behavior**
One or more logins for the website should show at the input fields from the database containing the entry.

**Version numbers:**
```
Mac OS X 10.11.5
Firefox 47.0.1
PassIFox 11 June 2016
KeePassX 2.0.2
Qt 5.6.4
libgcrypt 1.7.1
```
Built using Homebrew. My formula looks like this, most of it copied from @eugenesan's [old formula](https://github.com/eugenesan/homebrew-pfa/blob/master/Library/Formula/keepassx.rb).
```
require 'formula'

class KeepassxHttp < Formula
  homepage 'http://www.keepassx.org'
  url "https://github.com/droidmonkey/keepassx_http.git", :branch => "master"

  depends_on 'cmake'
  depends_on 'qt5'
  depends_on 'libgcrypt'
  depends_on 'libmicrohttpd'
  depends_on 'qjson'
  depends_on 'oath-toolkit'

  def install
    mkdir 'build' do
      system 'cmake', '..', *std_cmake_args

      # Do no deploy redundent Qt libs (we do not attempt .dmg bundle since the proccess is broken)
      inreplace 'src/cmake_install.cmake', 'FIXUP_QT4_EXECUTABLE', '#FIXUP_QT4_EXECUTABLE'

      system 'make', 'install'
    end
  end
end
```

**Comment by droidmonkey** [comment]
Is this running on a Mac? I cannot replicate this crash on Linux.

**Comment by anonymousreport1** [comment]
Yes, this is on Mac. I verified the installed browser plugin is [1.2.0](https://addons.mozilla.org/en-US/firefox/addon/passifox/).

I have recompiled KeePassX-http and it seems like the issue is **resolved** already. What I noticed is that I am now using QT 5.6.1 instead of 5.6.4.

```
KeePassX 2.0.2
Qt 5.6.1
libgcrypt 1.7.2
```

**Comment by droidmonkey** [comment]
OK, if it comes back make a new report, thank you!
