### ISSUE TITLE
Can't build from source in ubuntu 16 x64

### ISSUE THREAD

**Issue by heX16** [droidmonkey/keepassx_http#4]
hex@hex:~/workbench/keepassx_http-2.0.2/src$ mkdir build
hex@hex:~/workbench/keepassx_http-2.0.2/src$ ls
autotype        CMakeFiles               core    gui       streams
build           CMakeLists.txt           crypto  keys      version.h.cmake
CMakeCache.txt  config-keepassx.h.cmake  format  main.cpp
hex@hex:~/workbench/keepassx_http-2.0.2/src$ cd build
hex@hex:~/workbench/keepassx_http-2.0.2/src/build$ cmake -DWITH_TESTS=OFF ..
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
CMake Error at /usr/share/cmake-3.5/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:151 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/hex/workbench/keepassx_http-2.0.2/src/CMakeFiles/CMakeOutput.log".

**Comment by droidmonkey** [comment]
You need to install the Qt development files, I believe the package on ubuntu is: qt5-qmake
